class
type
def
self
self?
void
any
untyped
top
bot
instance
bool
nil
singleton
interface
end
include
extend
prepend
module
attr_reader
attr_writer
attr_accessor
super
public
private
alias
extension
incompatible
unchecked
out
in
