class Foo
  def ===: () -> bool
  def ==: () -> bool
  def =~: () -> bool
  def !~: () -> bool
  def !=: () -> bool
  def >=: () -> bool
  def <<: () -> bool
  def <=>: () -> bool
  def <=: () -> bool
  def >>: () -> bool
  def >: () -> bool
  def ~: () -> bool
  def +@: () -> bool
  def +: () -> bool
  def []=: () -> bool
  def []: () -> bool
  def -@: () -> bool
  def -: () -> bool
  def /: () -> bool
  def `: () -> bool
  def %: () -> bool
end
