class Foo
  include Bar
  extend Bar
  prepend Bar[A]
  prepend ::Bar
end

module Foo
  include ::Bar
  extend ::Bar[A, B]
  prepend ::Bar
end

interface _Foo
  include ::Bar::baz[A, B]
  extend ::Bar::baz
  prepend ::Bar::baz
  prepend Bar::baz
end

extension Foo(bar)
  include Bar::baz
  extend Bar::Baz
  prepend Bar::baz
end
