type Foo = A?
type Foo = int?
type Foo = ::Foo?
type Foo = Foo::Bar?
type Foo = self?
type Foo = self??
type Foo = (A | B)
type Foo = (A | B)?
type Foo = (A? | B)
type Foo = (A? | B)?
type Foo = (A | B?)
type Foo = (A | B?)?
type Foo = (A? | B?)
type Foo = (A? | B?)?
type Foo = (A? | B? | C?)?
type Foo = [A, B]
type Foo = [A, B]?
type Foo = [A?, B]
type Foo = [A?, B]?
type Foo = [A, B?]
type Foo = [A, B?]?
type Foo = [A?, B?]
type Foo = [A?, B?]?
