type Foo = :symbol
type Foo = "string"
type Foo = 42
type Foo = any
type Foo = bool
type Foo = bottom
type Foo = class
type Foo = false
type Foo = instance
type Foo = nil
type Foo = self
type Foo = self?
type Foo = top
type Foo = true
type Foo = untyped
type Foo = void
